services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    restart: unless-stopped
    user: root
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:50000:50000"
    volumes:
      - ~/.docker:/root/.docker
      - /usr/bin/docker:/usr/bin/docker
      - /run/docker.sock:/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
